version: "3.7"
networks:
  kong-net:
    driver: bridge
services:
  kong-db:
    image: postgres:9.6
    environment: 
      POSTGRES_USER: kong
      POSTGRES_DB: kong
    expose:
      - "5432"
    networks:
      kong-net:
        aliases:
          - kong-database
  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001, 0.0.0.0:8444 ssl'
    command: kong migrations bootstrap
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    networks:
      kong-net:
        aliases:
          - kong
